INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Thành phố Cần Thơ', '12345678', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Thành phố Hà Nội', '12387367', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Thành phố Hải Phòng', '12443531', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Thành phố Hồ Chí Minh', '12482522', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Thành phố Đà Nẵng', '12536695', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh An Giang', '12587843', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bà Rịa - Vũng Tàu', '12625603', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bắc Giang', '12654303', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bắc Kạn', '12671636', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bạc Liêu', '12720086', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bắc Ninh', '12753839', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bến Tre', '12772859', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bình Dương', '12818832', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bình Phước', '12850422', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bình Thuận', '12891731', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Bình Định', '12939874', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Cà Mau', '12993435', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Cao Bằng', '13024875', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Gia Lai', '13066479', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hà Giang', '13084225', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hà Nam', '13130384', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hà Tĩnh', '13152724', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hải Dương', '13201571', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hậu Giang', '13223077', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hòa Bình', '13275797', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Hưng Yên', '13332238', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Khánh Hòa', '13346842', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Kiên Giang', '13394915', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Kon Tum', '13418373', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Lai Châu', '13436853', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Lâm Đồng', '13467847', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Lạng Sơn', '13492786', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Lào Cai', '13538635', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Long An', '13555097', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Nam Định', '13603127', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Nghệ An', '13646678', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Ninh Bình', '13668276', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Ninh Thuận', '13708187', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Phú Thọ', '13726003', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Phú Yên', '13739027', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Quảng Bình', '13779292', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Quảng Nam', '13797420', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Quảng Ngãi', '13818626', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Quảng Ninh', '13853760', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Quảng Trị', '13871026', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Sóc Trăng', '13924729', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Sơn La', '13967616', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Tây Ninh', '13993441', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Thái Bình', '14025899', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Thái Nguyên', '14038415', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Thanh Hóa', '14089579', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Thừa Thiên Huế', '14129946', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Tiền Giang', '14173944', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Trà Vinh', '14217575', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Tuyên Quang', '14244414', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Vĩnh Long', '14277376', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Vĩnh Phúc', '14295659', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Yên Bái', '14312565', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Đắk Lắk', '14340873', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Đắk Nông', '14388676', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Điện Biên', '14436984', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Đồng Nai', '14486804', 'ACTIVE');
INSERT INTO `provinces` (`name`, `code`, `status`) VALUES ('Tỉnh Đồng Tháp', '14532494', 'ACTIVE');
